SELECT
  SRCH_KWD_HVAL,
  SRCH_KWD,
  ORG_CD,
  CASE WHEN CATE_SHC_YN = 'Y' THEN 1 ELSE 0 END AS CATE_SHC_YN,
  PP_SRW_INQ_CNT,
  MODEL_PPR,
  CATE_CD,
  CATE_SHC_PTH_NM,
  BOOK_YN,
  REG_DTM
FROM TB_SRCH_ATCP_KWD_DAT
WHERE ORG_CD != '4'
