select    /*+ PARALLEL(3) */
    ID,
    modelno,
    pl_no,
    modelno_group,
    CASE WHEN service_gubun='2' AND store_flag='1' AND ca_dept_code IS NOT NULL THEN RTRIM(category || ' '  || ca_dept_code) ELSE category END AS category,
    ca_code,
    CASE WHEN SUBSTR(RTRIM(ca_dept_code),3,8)='000000' OR SUBSTR(RTRIM(ca_dept_code),3,8) IS NULL THEN '' ELSE SUBSTR(RTRIM(ca_dept_code),0,4) END AS ca_dept_mcode,
    CASE WHEN SUBSTR(RTRIM(ca_dept_code),5,8)='0000' OR SUBSTR(RTRIM(ca_dept_code),5,8) IS NULL THEN '' ELSE SUBSTR(RTRIM(ca_dept_code),0,6) END AS ca_dept_code,
    CASE WHEN SUBSTR(RTRIM(ca_dept_code),7,8)='00' OR SUBSTR(RTRIM(ca_dept_code),7,8) IS NULL THEN '' ELSE SUBSTR(RTRIM(ca_dept_code),0,8) END AS ca_dept_dcode,
    ca_lcode_ran,
    ca_mcode_ran,
    ca_scode_ran,
    ca_dcode_ran,
    shop_code,    
    shop_name,    
    shop_name_code,
    modelnm,
    modelnm2,
    factory,
    brand,
    popular,
    popular2,
    sale_cnt,
    model_factory,
    minprice,
    maxprice,
    replace(minprices, ' ', '    ') as minprices,
    C_DATE,
    mallcnt,
    replace(replace(spec,',',' '),'/',' ') spec,
    openexpectflag,
    replace(condiname, ' ', '    ') as condiname,    
    CASE WHEN socialprice=0 THEN keyword ELSE keyword || ' ' || dbenuri.UDF_SOCIAL_GOODSNM(modelno_group,modelno) END AS KEYWORD,    
    keyword2,
    BRANDCODE1,
    BRANDCODE2,
    SPECOPT,
    bookflag,
    useflag,
    weight,
    minprice3,
    minprice2,
    maxprice3,
    mobile_flag,
    minprice4,
    store_flag,
    bbs_num,
    zum_check,
    service_gubun,
    minprice5,
    ext_condi_flag
FROM (    
    select
    'G' || NVL(modelno_group,a.modelno) ID,
    NVL(modelno_group,a.modelno) modelno,    
    0 pl_no,
    CASE WHEN MAX(modelno_group) IS NULL OR NVL(MAX(modelno_group),0)=0 THEN '0' ELSE '1' END AS modelno_group,
    NVL(dbenuri.UDF_RTN_GET_CATEGORY3(NVL(modelno_group,a.modelno)), ' ') AS category,
    MIN(ca_code) AS ca_code,
    CASE WHEN MAX(NVL(minprice4,0)) > 0 THEN dbenuri.UDF_RTN_GET_DEPT_CA_CODE(MAX(a.modelno)) ELSE '' END AS ca_dept_code,
    SUBSTR(MIN(ca_code),0,2) AS ca_lcode_ran,
    SUBSTR(MIN(ca_code),0,4) AS ca_mcode_ran,
    SUBSTR(MIN(ca_code),0,6) AS ca_scode_ran,
    SUBSTR(MIN(ca_code),0,8) AS ca_dcode_ran,
    MAX(replace(replace(modelnm,replace(condiname,'.',''),''),'[]','')) modelnm,  
    dbenuri.UDF_MODEL_FACTORY(MAX(factory),MAX(brand), MAX(modelnm || '~!@' || condiname)) modelnm2,
     0 shop_code,    
    '' shop_name,    
    '' shop_name_code,
    LTRIM(RTRIM(MAX(factory))) factory,     
    LTRIM(RTRIM(MAX(brand))) brand,     
    CASE WHEN MAX(modelno_group) IS NULL THEN NVL(MAX(popular),0) ELSE NVL(MAX(sum_popular),0) END AS popular,    
    CASE WHEN MAX(modelno_group) IS NULL THEN NVL(MAX(popular),0) ELSE NVL(MAX(sum_popular),0) END AS popular2,    
    MAX(sale_cnt) sale_cnt,
    dbenuri.UDF_MODEL_FACTORY(MAX(factory),MAX(brand), MAX(modelnm || '~!@' || condiname)) model_factory,
    CASE WHEN NVL(MAX(modelno_group),0) = 0 OR NVL(MIN(minprice),0) > 0 THEN MIN(minprice) ELSE DBENURI.UDF_MODEL_GROUP_MINPRICE2(NVL(MAX(modelno_group),0)) END AS minprice,     
    MAX(minprice) maxprice,    
    CASE WHEN NVL(MAX(modelno_group),0) = 0 THEN MIN(minprice) || '' ELSE DBENURI.UDF_MODEL_GROUP_MINPRICE(NVL(MAX(modelno_group),0)) END AS minprices,    
    TO_CHAR(MIN(C_DATE),'YYYYMMDDHH24MISS') AS C_DATE,    
    MAX(mallcnt) mallcnt,    
    replace(replace(replace(replace(replace(MAX(spec),'/',' '),',',' '),'(',' '),')',' '),'+',' ') spec,
    case when NVL(MIN(openexpectflag),'0')  = '1' or  min(c_date) > sysdate  then '1' else '0' end as openexpectflag, 
    CASE WHEN NVL(MAX(modelno_group),0) = 0 THEN '' ELSE DBENURI.UDF_MODEL_GROUP_CONDINAME(NVL(MAX(modelno_group),0)) END AS condiname,     
    CASE WHEN NVL(MAX(modelno_group),0) = 0 THEN NVL(MAX(KEYWORD), '') || ' ' || NVL(MAX(BRAND),'') ELSE DBENURI.UDF_MODEL_GROUP_KEYWORD(NVL(MAX(modelno_group),0)) || ' ' || NVL(MAX(BRAND),'') END AS KEYWORD,     
    dbenuri.UDF_CATEGORY_KEYWORD_POPULAR2(MIN(a.modelno)) AS keyword2,
    '' AS BRANDCODE1,     
    '' AS BRANDCODE2,     
    dbenuri.UDF_RTN_GET_SPECOPT(NVL(modelno_group,a.modelno)) AS SPECOPT, 
    CASE WHEN MAX(substr(ca_code,0,2)) = '93' then '1' else '0' end as bookflag ,
    CASE WHEN  MAX(mallcnt) > 0 and   (case when NVL(MIN(openexpectflag),'0')  = '1' or  min(c_date) > sysdate  then '1' else '0' end) = '0' and MAX(substr(ca_code,0,2)) <> '93' then '1' else '0' end as useflag,
    CASE WHEN substr(MAX(ca_code),0,4)='0501' then NVL(MAX(weight)*100,0) else NVL(MAX(weight)*100,999999) end as weight,
    NVL(MIN(socialprice),0) socialprice,
    CASE WHEN NVL(MAX(modelno_group),0) > 0 AND MAX(NVL(minprice3,0)) > 0 THEN dbenuri.UDF_MODEL_GROUP_MINPRICE_ETC(MAX(modelno_group),3) ELSE MIN(minprice3) END AS minprice3,
    CASE WHEN NVL(MAX(modelno_group),0) > 0 AND MAX(NVL(minprice2,0)) > 0 THEN dbenuri.UDF_MODEL_GROUP_MINPRICE_ETC(MAX(modelno_group),2) ELSE MIN(minprice2) END AS minprice2,    
    MAX(minprice3) maxprice3, 
    '1' mobile_flag,
    CASE WHEN NVL(MAX(modelno_group),0) > 0 AND MAX(NVL(minprice4,0)) > 0 THEN dbenuri.UDF_MODEL_GROUP_MINPRICE_ETC(MAX(modelno_group),4) ELSE MIN(minprice4) END AS minprice4,
    CASE WHEN MIN(NVL(minprice4,0)) > 0 then '1' else '0' end as store_flag ,
    dbenuri.UDF_BBS_NUM_SUM(NVL(modelno_group,a.modelno)) bbs_num, 
    '1' zum_check,   
    '1' service_gubun,
    dbenuri.UDF_MODEL_GROUP_MINPRICE_ETC(NVL(MAX(modelno_group),0),5) AS minprice5,
    NVL(MIN(EXT_CONDI_FLAG),'0') as ext_condi_flag
    from dbenuri.tbl_goods a join dbenuri.tbl_cate_goods b on a.modelno = b.modelno  join dbenuri.tbl_goods_sum c on a.modelno = c.modelno
    WHERE jobcode>='1'    
    AND (constrain = '1' OR (constrain = '5' AND mallcnt > 0))
    AND cateflag='0'    
    and mod(nvl(modelno_group,a.modelno), 6) = 1
    GROUP BY nvl(modelno_group,a.modelno)    
    UNION ALL
    SELECT
    'P' || P.pl_no ID,    
    P.pl_no MODELNO, 
    P.PL_NO pl_no,
    '0' modelno_group,
    CASE WHEN P.CA_CODE IS NULL THEN '000000' WHEN LENGTH(RTRIM(P.CA_CODE))=2 THEN RTRIM( P.CA_CODE) || '0000' WHEN LENGTH(RTRIM(P.CA_CODE))=4 THEN RTRIM(P.CA_CODE) || '00' ELSE P.CA_CODE END AS CATEGORY,
    CASE WHEN P.CA_CODE IS NULL THEN '000000' WHEN LENGTH(RTRIM(P.CA_CODE))=2 THEN RTRIM( P.CA_CODE) || '0000' WHEN LENGTH(RTRIM(P.CA_CODE))=4 THEN RTRIM(P.CA_CODE) || '00' ELSE P.CA_CODE END AS CA_CODE,
    CASE WHEN store_flag='1' THEN ca_code_dept ELSE '' END AS ca_dept_code, 
    '' AS ca_lcode_ran,
    '' AS ca_mcode_ran,
    '' AS ca_scode_ran,
    '' AS ca_dcode_ran,
    CASE WHEN SUBSTR(P.CA_CODE,0,4) = '9501' then dbenuri.UDF_GOODSNM_REMOVE(P.goodsnm) || ' 음반 앨범' else dbenuri.UDF_GOODSNM_REMOVE(P.goodsnm) end as modelnm ,
    CASE WHEN SUBSTR(P.CA_CODE,0,4) = '1219' THEN dbenuri.UDF_GOODSNM_REMOVE(P.goodsnm) ELSE '' END AS modelnm2,
    P.shop_code,    
    S.shop_name,    
    '' as shop_name_code,
    '[추가]' factory,   
    '기타' brand,
    NVL(P.POPULAR,0) AS POPULAR,
    NVL(P.POPULAR,0) AS POPULAR2,
        sale_cnt,
    '' model_factory,
    P.price minprice,    
    P.price maxprice,
    P.price || ' ' minprices,    
    TO_CHAR(P.U_DATE,'YYYYMMDDHH24MISS') AS C_DATE,    
    1 mallcnt,    
    ' ' spec,
    '0' openexpectflag,
    ' ' condiname,
    ' ' keyword,
    ' ' keyword2,
    ' ' brandcode1,
    ' ' brandcode2,
    ' ' specopt,
    CASE WHEN SUBSTR(P.CA_CODE,0,2) = '93' then '1' else '0' end as bookflag ,
    CASE WHEN SUBSTR(P.CA_CODE,0,2) = '93' then '0' else '1' end as useflag,
    0 weight,
    0 socialprice,
    (case when NVL(instance_price,0) = 0 then price else case when instance_price < price then instance_price else price end end) minprice3,
    CASE WHEN deliverytype2=0 THEN (price + 2500) ELSE (price + DECODE(deliveryinfo, '무료배송', 0, NVL(deliveryinfo2, 2500))) END minprice2,
    NVL(instance_price,0) maxprice3,
    CASE WHEN NVL(instance_price,0) = 0 then '0' else '1' end as mobile_flag,    
    CASE WHEN NVL(store_flag,'0')='1' THEN price ELSE 0 END AS minprice4,
    NVL(store_flag,'0') store_flag,
    0 bbs_num,
    DBENURI.UDF_ZUM_CHECK(P.shop_code) zum_check,
    '2' service_gubun,
    P.price minprice5,
    '0' as ext_condi_flag
    FROM   dbenuri.TBL_PRICELIST P  
      INNER JOIN dbenuri.TBL_SHOPLIST S    
      ON P.SHOP_CODE = S.SHOP_CODE    
      LEFT OUTER JOIN dbenuri.TBL_GOODS G    
      ON P.MODELNO = G.MODELNO    
      join dbenuri.tbl_cate_goods c on g.modelno = c.modelno   AND c.CATEFLAG='0'
      join dbenuri.tbl_goods_sum t on g.modelno = t.modelno
    WHERE  P.SRVFLAG in ('0','L','R','Z','2','3','6','7','9','O','D','S','P')  
    --AND SUBSTR(P.CA_CODE,0,4) <> '8702' 
    AND (
      P.modelno<=0        
      OR ( G.CONSTRAIN='1' AND G.JOBCODE = '0' )        
      OR ( G.CONSTRAIN IS NULL AND G.JOBCODE IS NULL )        
      OR G.CONSTRAIN IN ('2','3')
      OR (P.option_flag2='1' AND t.minprice < P.price)
      OR P.SRVFLAG IN ('Z','2','3','6','7','9','O','D','P')
    )        
    and mod(pl_no, 6) = 1
 )

