select
    status as action,
    search_key as ID,
    modelno,
    pl_no,
    modelno_group,
    MODELNO_GROUP_FLAG,
    category,
    CG,
    CAT1,
    CAT2,
    CAT3,
    CAT4,
    ca_code,
    ca_dept_mcode,
    ca_dept_code,
    ca_dept_dcode,
    ca_lcode_ran,
    ca_mcode_ran,
    ca_scode_ran,
    ca_dcode_ran,
    shop_code,
    shop_name,
    shop_name_code,
    modelnm,
    modelnm2,
    factory,
    brand,
    popular,
    popular2,
    sale_cnt,
    model_factory,
    minprice,
    maxprice,
    minprices,
    C_DATE,
    mallcnt,
    MALLCNT_FLAG,
    spec,
    openexpectflag,
    condiname,
    KEYWORD,
    keyword2,
    BRANDCODE1,
    BRANDCODE2,
    SPECOPT,
    bookflag,
    useflag,
    weight,
    minprice3,
    minprice2,
    maxprice3,
    mobile_flag,
    minprice4,
    store_flag,
    bbs_num,
    zum_check,
    service_gubun,
    minprice5,
    ext_condi_flag,
    MODELNM || ' ' || FACTORY || ' ' || SPEC || ' ' || KEYWORD || ' ' || KEYWORD2 || ' ' || CONDINAME AS to_all
from dbenuri.TBL_SEARCH_LOG_ES
where regdate > :sql_last_value
--where
-- (case when modelno=0 then mod(pl_no, 3) else mod(modelno, 3) end) = 0
-- and regdate < (select stime from DBENURI.ir_inc_index_timestamp where collection_name = 'ENURI_0')
